//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenixBack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jovem
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> idade { get; set; }
        public string possuiTranstorno { get; set; }
        public string descricaoTranstorno { get; set; }
        public string descricaoEstadoSaude { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public Nullable<bool> ligadoDesligado { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string endereco { get; set; }
        public Nullable<System.DateTime> dataEntrada { get; set; }
        public Nullable<System.DateTime> dataSaida { get; set; }
    }
}
