//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenixBack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public bool ligadoDesligado { get; set; }
        public string usuario1 { get; set; }
        public string cpf { get; set; }
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
        public Nullable<System.DateTime> dataEntrada { get; set; }
        public Nullable<System.DateTime> dataSaida { get; set; }
        public string sexo { get; set; }
    
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
