//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenixBack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int idVisita { get; set; }
        public string nomeVisitante { get; set; }
        public string cpfVisitante { get; set; }
        public string TELVisitante { get; set; }
        public System.DateTime dataVisita { get; set; }
        public System.TimeSpan horaVisita { get; set; }
        public Nullable<int> idJovemVisitado { get; set; }
        public Nullable<int> numOrdemJudicial { get; set; }
        public Nullable<short> tipoVisita { get; set; }
    
        public virtual Jovem Jovem { get; set; }
    }
}
